CREATE TABLE `annotations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`screenshotId` int NOT NULL,
	`annotationType` enum('line','angle','circle','text') NOT NULL,
	`data` json NOT NULL,
	`color` varchar(20) DEFAULT '#ff0000',
	`label` varchar(255),
	`measuredValue` float,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `annotations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`assessmentDate` varchar(20) NOT NULL,
	`status` enum('draft','in_progress','completed') NOT NULL DEFAULT 'draft',
	`trainingFrequency` varchar(255),
	`weeklyMileage` varchar(255),
	`runningGoals` text,
	`runningExperience` text,
	`currentPace` varchar(100),
	`preferredTerrain` varchar(255),
	`shoeType` varchar(255),
	`injuries` json,
	`concerns` text,
	`backgroundNotes` text,
	`inbodyScore` float,
	`totalBodyWater` float,
	`protein` float,
	`mineral` float,
	`bodyFatMass` float,
	`bodyWeight` float,
	`skeletalMuscleMass` float,
	`bmi` float,
	`percentBodyFat` float,
	`waistHipRatio` float,
	`visceralFatLevel` int,
	`basalMetabolicRate` float,
	`segmentalLean` json,
	`segmentalFat` json,
	`inbodyNotes` text,
	`vo2max` float,
	`maxSpeed` float,
	`maxHeartRate` int,
	`maxVentilation` float,
	`tidalVolume` float,
	`respiratoryFrequency` int,
	`vt1HeartRate` int,
	`vt1Speed` float,
	`vt1Calories` float,
	`vt2HeartRate` int,
	`vt2Speed` float,
	`vt2Calories` float,
	`vo2maxPercentile` int,
	`trainingZones` json,
	`vo2Notes` text,
	`clinicalImpression` text,
	`thingsToImprove` text,
	`managementPlan` text,
	`runningCues` text,
	`mobilityExercises` text,
	`strengthExercises` text,
	`runningProgramming` text,
	`aiGeneratedReport` text,
	`reportJson` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assessments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `metricsStandards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`metricName` varchar(100) NOT NULL,
	`metricCategory` varchar(100) NOT NULL,
	`unit` varchar(50),
	`description` text,
	`needsImprovementMin` float,
	`needsImprovementMax` float,
	`acceptableMin` float,
	`acceptableMax` float,
	`excellentMin` float,
	`excellentMax` float,
	`isHigherBetter` boolean DEFAULT true,
	`isActive` boolean DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `metricsStandards_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`dateOfBirth` varchar(20),
	`gender` varchar(20),
	`height` float,
	`weight` float,
	`email` varchar(320),
	`phone` varchar(50),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `screenshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assessmentId` int NOT NULL,
	`viewType` enum('side_left','side_right','back') NOT NULL,
	`gaitPhase` enum('foot_strike','loading','push_off','swing','other') NOT NULL,
	`imageUrl` text NOT NULL,
	`thumbnailUrl` text,
	`timestamp` float,
	`description` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `screenshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `videos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`assessmentId` int NOT NULL,
	`viewType` enum('side_left','side_right','back') NOT NULL,
	`videoUrl` text NOT NULL,
	`fileName` varchar(500),
	`durationSeconds` float,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `videos_id` PRIMARY KEY(`id`)
);
