ALTER TABLE `assessments` ADD `inbodyFileUrl` text;--> statement-breakpoint
ALTER TABLE `assessments` ADD `inbodyFileName` varchar(500);--> statement-breakpoint
ALTER TABLE `assessments` ADD `vo2FileUrl` text;--> statement-breakpoint
ALTER TABLE `assessments` ADD `vo2FileName` varchar(500);--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `inbodyScore`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `totalBodyWater`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `protein`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `mineral`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `bodyFatMass`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `bodyWeight`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `skeletalMuscleMass`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `bmi`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `percentBodyFat`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `waistHipRatio`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `visceralFatLevel`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `basalMetabolicRate`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `segmentalLean`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `segmentalFat`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vo2max`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `maxSpeed`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `maxHeartRate`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `maxVentilation`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `tidalVolume`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `respiratoryFrequency`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vt1HeartRate`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vt1Speed`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vt1Calories`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vt2HeartRate`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vt2Speed`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vt2Calories`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `vo2maxPercentile`;--> statement-breakpoint
ALTER TABLE `assessments` DROP COLUMN `trainingZones`;